name: Java CD

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v1
       
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
            
       - name: Deploy to GitHub packages
         # Have to skip doc and sources because GH Packages doesn't support classifiers
         run: mvn -B clean deploy -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
         env:
            GITHUB_TOKEN: ${{ github.token }}