name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v1
       
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       
       - name: Validate version
         run: mvn -B validate
       
       - name: Build with Maven
         run: mvn -B clean package -DskipTests
         
       - name: Collect artifacts
         uses: actions/upload-artifact@v2
         with:
            name: generated-artifacts
            path: target/*.jar
   
  test:
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v1
       
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       
       - name: Validate version
         run: mvn -B validate
       
       - name: Run unit tests
         run: mvn -B clean test