name: builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v1
       
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
           
       - name: Build with Maven
         run: mvn -B clean package -DskipTests
         
       - name: Run unit tests
         run: mvn -B test
           
       - name: Deploy to GitHub packages
         run: mvn -B deploy
         env:
            GITHUB_TOKEN: ${{ github.token }}
