name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - name: Deploy to GH packages
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/MRtecno98 -Dtoken=${{ secrets.GITHUB_TOKEN }}
